<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Minifier\Module'                        => __DIR__ . '/Module.php',
    'Minifier\Controller\SkeletonController' => __DIR__ . '/src/Minifier/Controller/MinifierController.php',
    'Minifier\Framework\TestCase'        => __DIR__ . '/tests/ZendSkeletonModule/Framework/TestCase.php',
    'Minifier\SampleTest'                => __DIR__ . '/tests/ZendSkeletonModule/SampleTest.php',
);