<div class="zdt-toolbar-entry">
    <div class="zdt-toolbar-preview">
        <i class="icon-user icon-white"></i>
        <span class="zdt-toolbar-info time">
            <span class="display"><?=$this->collector->getLocation() ?></span>
        </span>
    </div>
    <div class="zdt-toolbar-detail">
        <!-- <span class="zdt-toolbar-info">
            <span class="zdt-detail-label">Total time:</span>
            <span class="zdt-detail-value"></span>
        </span>
        <span class="zdt-toolbar-info">
            <span class="zdt-detail-label">Queries count:</span>
            <span class="zdt-detail-value"></span>
        </span> -->
    </div>

</div>
